<?php

function protherics_register_cpt_insights() {
    $labels = array(
        'name'                  => _x( 'Insights', 'protherics' ),
        'singular_name'         => _x( 'Insight', 'protherics' ),
        'menu_name'             => __( 'Insights', 'protherics' ),
        'name_admin_bar'        => __( 'Insights', 'protherics' ),
        'archives'              => __( 'Item Archives', 'protherics' ),
		'attributes'            => __( 'Item Attributes', 'protherics' ),
		'parent_item_colon'     => __( 'Parent Item:', 'protherics' ),
		'all_items'             => __( 'All Items', 'protherics' ),
		'add_new_item'          => __( 'Add New Item', 'protherics' ),
		'add_new'               => __( 'Add New', 'protherics' ),
		'new_item'              => __( 'New Item', 'protherics' ),
		'edit_item'             => __( 'Edit Item', 'protherics' ),
		'update_item'           => __( 'Update Item', 'protherics' ),
		'view_item'             => __( 'View Item', 'protherics' ),
		'view_items'            => __( 'View Items', 'protherics' ),
		'search_items'          => __( 'Search Item', 'protherics' ),
		'not_found'             => __( 'Not found', 'protherics' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'protherics' ),
		'featured_image'        => __( 'Featured Image', 'protherics' ),
		'set_featured_image'    => __( 'Set featured image', 'protherics' ),
		'remove_featured_image' => __( 'Remove featured image', 'protherics' ),
		'use_featured_image'    => __( 'Use as featured image', 'protherics' ),
		'insert_into_item'      => __( 'Insert into item', 'protherics' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'protherics' ),
		'items_list'            => __( 'Items list', 'protherics' ),
		'items_list_navigation' => __( 'Items list navigation', 'protherics' ),
		'filter_items_list'     => __( 'Filter items list', 'protherics' ),
    );
    $args = array(
		'label'                 => __( 'Insights', 'protherics' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
		'taxonomies'            => array(),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_rest'			=> true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => true,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'menu_icon'             => 'dashicons-grid-view',
	);
	register_post_type( 'insights', $args );
}
add_action( 'init', 'protherics_register_cpt_insights', 0 );


function protherics_register_cpt_members() {
    $labels = array(
        'name'                  => _x( 'Members', 'protherics' ),
        'singular_name'         => _x( 'Member', 'protherics' ),
        'menu_name'             => __( 'Members', 'protherics' ),
        'name_admin_bar'        => __( 'Members', 'protherics' ),
        'archives'              => __( 'Item Archives', 'protherics' ),
		'attributes'            => __( 'Item Attributes', 'protherics' ),
		'parent_item_colon'     => __( 'Parent Item:', 'protherics' ),
		'all_items'             => __( 'All Items', 'protherics' ),
		'add_new_item'          => __( 'Add New Item', 'protherics' ),
		'add_new'               => __( 'Add New', 'protherics' ),
		'new_item'              => __( 'New Item', 'protherics' ),
		'edit_item'             => __( 'Edit Item', 'protherics' ),
		'update_item'           => __( 'Update Item', 'protherics' ),
		'view_item'             => __( 'View Item', 'protherics' ),
		'view_items'            => __( 'View Items', 'protherics' ),
		'search_items'          => __( 'Search Item', 'protherics' ),
		'not_found'             => __( 'Not found', 'protherics' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'protherics' ),
		'featured_image'        => __( 'Featured Image', 'protherics' ),
		'set_featured_image'    => __( 'Set featured image', 'protherics' ),
		'remove_featured_image' => __( 'Remove featured image', 'protherics' ),
		'use_featured_image'    => __( 'Use as featured image', 'protherics' ),
		'insert_into_item'      => __( 'Insert into item', 'protherics' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'protherics' ),
		'items_list'            => __( 'Items list', 'protherics' ),
		'items_list_navigation' => __( 'Items list navigation', 'protherics' ),
		'filter_items_list'     => __( 'Filter items list', 'protherics' ),
    );
    $args = array(
		'label'                 => __( 'Members', 'protherics' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
		'taxonomies'            => array(),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_rest'			=> true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => true,
		'publicly_queryable'    => false,
		'capability_type'       => 'page',
		'menu_icon'             => 'dashicons-admin-users',
	);
	register_post_type( 'members', $args );
}
add_action( 'init', 'protherics_register_cpt_members', 0 );

function protherics_register_cpt_news() {
    $labels = array(
        'name'                  => _x( 'News', 'protherics' ),
        'singular_name'         => _x( 'News', 'protherics' ),
        'menu_name'             => __( 'News', 'protherics' ),
        'name_admin_bar'        => __( 'News', 'protherics' ),
        'archives'              => __( 'Item Archives', 'protherics' ),
		'attributes'            => __( 'Item Attributes', 'protherics' ),
		'parent_item_colon'     => __( 'Parent Item:', 'protherics' ),
		'all_items'             => __( 'All Items', 'protherics' ),
		'add_new_item'          => __( 'Add New Item', 'protherics' ),
		'add_new'               => __( 'Add New', 'protherics' ),
		'new_item'              => __( 'New Item', 'protherics' ),
		'edit_item'             => __( 'Edit Item', 'protherics' ),
		'update_item'           => __( 'Update Item', 'protherics' ),
		'view_item'             => __( 'View Item', 'protherics' ),
		'view_items'            => __( 'View Items', 'protherics' ),
		'search_items'          => __( 'Search Item', 'protherics' ),
		'not_found'             => __( 'Not found', 'protherics' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'protherics' ),
		'featured_image'        => __( 'Featured Image', 'protherics' ),
		'set_featured_image'    => __( 'Set featured image', 'protherics' ),
		'remove_featured_image' => __( 'Remove featured image', 'protherics' ),
		'use_featured_image'    => __( 'Use as featured image', 'protherics' ),
		'insert_into_item'      => __( 'Insert into item', 'protherics' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'protherics' ),
		'items_list'            => __( 'Items list', 'protherics' ),
		'items_list_navigation' => __( 'Items list navigation', 'protherics' ),
		'filter_items_list'     => __( 'Filter items list', 'protherics' ),
    );
    $args = array(
		'label'                 => __( 'News', 'protherics' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
		'taxonomies'            => array(),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_rest'			=> true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => true,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'menu_icon'             => 'dashicons-admin-site-alt2',
	);
	register_post_type( 'news', $args );
}
add_action( 'init', 'protherics_register_cpt_news', 0 );

function protherics_register_cpt_locations() {
    $labels = array(
        'name'                  => _x( 'Locations', 'protherics' ),
        'singular_name'         => _x( 'Locations', 'protherics' ),
        'menu_name'             => __( 'Locations', 'protherics' ),
        'name_admin_bar'        => __( 'Locations', 'protherics' ),
        'archives'              => __( 'Item Archives', 'protherics' ),
		'attributes'            => __( 'Item Attributes', 'protherics' ),
		'parent_item_colon'     => __( 'Parent Item:', 'protherics' ),
		'all_items'             => __( 'All Items', 'protherics' ),
		'add_new_item'          => __( 'Add New Item', 'protherics' ),
		'add_new'               => __( 'Add New', 'protherics' ),
		'new_item'              => __( 'New Item', 'protherics' ),
		'edit_item'             => __( 'Edit Item', 'protherics' ),
		'update_item'           => __( 'Update Item', 'protherics' ),
		'view_item'             => __( 'View Item', 'protherics' ),
		'view_items'            => __( 'View Items', 'protherics' ),
		'search_items'          => __( 'Search Item', 'protherics' ),
		'not_found'             => __( 'Not found', 'protherics' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'protherics' ),
		'featured_image'        => __( 'Featured Image', 'protherics' ),
		'set_featured_image'    => __( 'Set featured image', 'protherics' ),
		'remove_featured_image' => __( 'Remove featured image', 'protherics' ),
		'use_featured_image'    => __( 'Use as featured image', 'protherics' ),
		'insert_into_item'      => __( 'Insert into item', 'protherics' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'protherics' ),
		'items_list'            => __( 'Items list', 'protherics' ),
		'items_list_navigation' => __( 'Items list navigation', 'protherics' ),
		'filter_items_list'     => __( 'Filter items list', 'protherics' ),
    );
    $args = array(
		'label'                 => __( 'Locations', 'protherics' ),
		'labels'                => $labels,
		'supports'              => array( 'title' ),
		'taxonomies'            => array(),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_rest'			=> true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => true,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'menu_icon'             => 'dashicons-post-status',
	);
	register_post_type( 'locations', $args );
}
add_action( 'init', 'protherics_register_cpt_locations', 0 );

function protherics_register_cpt_products() {
    $labels = array(
        'name'                  => _x( 'Products', 'protherics' ),
        'singular_name'         => _x( 'Product', 'protherics' ),
        'menu_name'             => __( 'Products', 'protherics' ),
        'name_admin_bar'        => __( 'Products', 'protherics' ),
        'archives'              => __( 'Item Archives', 'protherics' ),
		'attributes'            => __( 'Item Attributes', 'protherics' ),
		'parent_item_colon'     => __( 'Parent Item:', 'protherics' ),
		'all_items'             => __( 'All Items', 'protherics' ),
		'add_new_item'          => __( 'Add New Item', 'protherics' ),
		'add_new'               => __( 'Add New', 'protherics' ),
		'new_item'              => __( 'New Item', 'protherics' ),
		'edit_item'             => __( 'Edit Item', 'protherics' ),
		'update_item'           => __( 'Update Item', 'protherics' ),
		'view_item'             => __( 'View Item', 'protherics' ),
		'view_items'            => __( 'View Items', 'protherics' ),
		'search_items'          => __( 'Search Item', 'protherics' ),
		'not_found'             => __( 'Not found', 'protherics' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'protherics' ),
		'featured_image'        => __( 'Featured Image', 'protherics' ),
		'set_featured_image'    => __( 'Set featured image', 'protherics' ),
		'remove_featured_image' => __( 'Remove featured image', 'protherics' ),
		'use_featured_image'    => __( 'Use as featured image', 'protherics' ),
		'insert_into_item'      => __( 'Insert into item', 'protherics' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'protherics' ),
		'items_list'            => __( 'Items list', 'protherics' ),
		'items_list_navigation' => __( 'Items list navigation', 'protherics' ),
		'filter_items_list'     => __( 'Filter items list', 'protherics' ),
    );
    $args = array(
		'label'                 => __( 'Products', 'protherics' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'thumbnail' ),
		'taxonomies'            => array(),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_rest'			=> true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => true,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'menu_icon'             => 'dashicons-cart',
	);
	register_post_type( 'products', $args );
}
add_action( 'init', 'protherics_register_cpt_products', 0 );


function protherics_register_cpt_region() {
	$labels = array(
		'name'                  => _x( 'Regions', 'protherics' ),
		'singular_name'         => _x( 'Region', 'protherics' ),
		'menu_name'             => __( 'Regions', 'protherics' ),
		'name_admin_bar'        => __( 'Regions', 'protherics' ),
		'archives'              => __( 'Item Archives', 'protherics' ),
		'attributes'            => __( 'Item Attributes', 'protherics' ),
		'parent_item_colon'     => __( 'Parent Item:', 'protherics' ),
		'all_items'             => __( 'All Items', 'protherics' ),
		'add_new_item'          => __( 'Add New Item', 'protherics' ),
		'add_new'               => __( 'Add New', 'protherics' ),
		'new_item'              => __( 'New Item', 'protherics' ),
		'edit_item'             => __( 'Edit Item', 'protherics' ),
		'update_item'           => __( 'Update Item', 'protherics' ),
		'view_item'             => __( 'View Item', 'protherics' ),
		'view_items'            => __( 'View Items', 'protherics' ),
		'search_items'          => __( 'Search Item', 'protherics' ),
		'not_found'             => __( 'Not found', 'protherics' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'protherics' ),
		'featured_image'        => __( 'Featured Image', 'protherics' ),
		'set_featured_image'    => __( 'Set featured image', 'protherics' ),
		'remove_featured_image' => __( 'Remove featured image', 'protherics' ),
		'use_featured_image'    => __( 'Use as featured image', 'protherics' ),
		'insert_into_item'      => __( 'Insert into item', 'protherics' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'protherics' ),
		'items_list'            => __( 'Items list', 'protherics' ),
		'items_list_navigation' => __( 'Items list navigation', 'protherics' ),
		'filter_items_list'     => __( 'Filter items list', 'protherics' ),
	);
	$args = array(
		'label'                 => __( 'Regions', 'protherics' ),
		'labels'                => $labels,
		'supports'              => array( 'title' ),
		'taxonomies'            => array(),
		'hierarchical'          => false,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_rest'          => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => true,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'menu_icon'             => 'dashicons-admin-site-alt3',
	);
	register_post_type( 'region', $args );
}
add_action( 'init', 'protherics_register_cpt_region', 0 );
